name: barseq
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python
  - conda-forge::anndata
  - h5py
  - imageio
  - ipython
  - joblib
  - jupyter
  - natsort
  - networkx
  - numpy
  - opencv
  - pandas
  - pyarrow
  - scikit-image
  - scipy
  - seaborn
  - tifffile

